apiVersion: apps/v1
kind: Deployment
metadata:
  name: microconfig-cli-dev
  namespace: default
  labels:
    app: microconfig-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microconfig-cli-dev
  template:
    metadata:
      labels:
        app: microconfig-cli-dev
    spec:
      serviceAccountName: vault-auth-dev
      containers:
        - name: microconfig-cli
          image: "microconfig/server-cli:latest_alpha"
          imagePullPolicy: Always
          command: ["sleep", "infinity"]
          env:
            - name: MCS_ADDRESS
              value: http://microconfig-server.default.svc.cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microconfig-cli-prod
  namespace: default
  labels:
    app: microconfig-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microconfig-cli-prod
  template:
    metadata:
      labels:
        app: microconfig-cli-prod
    spec:
      serviceAccountName: vault-auth-prod
      containers:
        - name: microconfig-cli
          image: "microconfig/server-cli:latest_alpha"
          imagePullPolicy: Always
          command: ["sleep", "infinity"]
          env:
            - name: MCS_ADDRESS
              value: http://microconfig-server.default.svc.cluster.local