apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-backend
  namespace: default
  labels:
    app: payment-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-backend
  template:
    metadata:
      labels:
        app: payment-backend
    spec:
      volumes:
        - name: config
          emptyDir: { }
      initContainers:
        - name: microconfig
          image: "microconfig/server-cli:latest_beta"
          imagePullPolicy: Always
          command: [ "/bin/sh","-c", "microctl save payment-backend -e dev -d /config" ]
          env:
            - name: MCS_ADDRESS
              value: http://microconfig-server.default.svc.cluster.local
          volumeMounts:
            - name: config
              mountPath: "/config"
      containers:
        - name: payment-backend
          image: "alpine:latest"
          imagePullPolicy: Always
          command: [ "sleep", "infinity" ]
          volumeMounts:
            - name: config
              mountPath: "/config"