apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vault
  name: vault
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: "vault:latest"
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
          ports:
            - containerPort: 8200
          env:
            - name: VAULT_ADDR
              value: http://0.0.0.0:8200
            - name: VAULT_API_ADDR
              value: http://0.0.0.0:8200
            - name: VAULT_ADDRESS
              value: http://0.0.0.0:8200
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vault
  name: vault
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: vault
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8200