spring:
  application.name: microconfig-server
  main:
    banner-mode: off
    allow-bean-definition-overriding: true

vault:
  address: http://127.0.0.1:8200

config:
  local: /Users/kapodes/microconfig/example

server:
  port: 8080

logging:
  level:
    root: INFO
    io.microconfig: TRACE
