spring:
  application:
    name: microconfig-server
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  mustache:
    check-template-location: false

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

logging:
  level:
    root: WARN
    org:
      springframework:
        boot:
          StartupInfoLogger: INFO
    io.microconfig: INFO

git:
  workingDir: ${WORK_DIR}
  remoteUrl: ${REMOTE_URL:https://github.com/microconfig/microconfig-server-quickstart.git}
  defaultBranch: ${DEFAULT_BRANCH:master}
  username: ${USERNAME:open}
  password: ${PASSWORD:source}
  pullDelay: 10
