1spring:
  application.name: microconfig-server
  main:
    banner-mode: off
    allow-bean-definition-overriding: true

logging:
  level:
    root: INFO
    io.microconfig: TRACE

server.port: 8080

git:
  workingDir: ${WORK_DIR}
  remoteUrl: ${REMOTE_URL}
  default-branch: ${DEFAULT_BRANCH:master}
  username: ${USERNAME:open}
  password: ${PASSWORD:source}