spring:
  application.name: microconfig-server
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  mustache:
    check-template-location: false

server:
  port: 80

git:
  workingDir: /microconfig
  remoteUrl: ${REMOTE_URL}
  default-branch: ${DEFAULT_BRANCH:master}
  username: ${USERNAME:open}
  password: ${PASSWORD:source}

logging:
  level:
    root: INFO
    io.microconfig: ${LOG_LEVEL:DEBUG}
