spring:
  application.name: microconfig-server
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  mustache:
    check-template-location: false

server:
  port: 80

git:
  workingDir: /microconfig
  remoteUrl: ${REMOTE_URL:https://github.com/microconfig/microconfig-quickstart.git}
  default-branch: ${CONFIG_BRANCH:master}
  username: ${USERNAME:open}
  password: ${PASSWORD:source}

logging:
  level:
    ROOT: WARN
    io.microconfig: ${LOG_LEVEL:DEBUG}
    org:
      springframework:
        boot:
          StartupInfoLogger: INFO