name: "Build Release"

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build Jar"
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build Jar
        run: ./gradlew shadowJar -p server-microctl
      - uses: actions/upload-artifact@v2
        with:
          name: microctl.jar
          path: server-microctl/build/libs/microctl.jar

  linux:
    name: "Build Linux Binary"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Download Jar
        uses: actions/download-artifact@v2
        with:
          name: microctl.jar
      - name: Install GraalVM Native Image
        shell: bash
        run: .github/scripts/native/graalvm-linux.sh
      - name: Build Binary
        shell: bash
        run: .graalvm/bin/native-image --static -jar microctl.jar
      - name: Test Run
        shell: bash
        run: ./microctl version
      - uses: actions/upload-artifact@v2
        with:
          name: microctl-linux
          path: ./microctl

  alpine:
    name: "Build Alpine Binary"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Download Jar
        uses: actions/download-artifact@v2
        with:
          name: microctl.jar
      - name: Install GraalVM Native Image
        shell: bash
        run: .github/scripts/native/graalvm-alpine.sh
      - name: Build Binary
        shell: bash
        run: PATH="$PWD/musl/bin:$PATH" .graalvm/bin/native-image --static --libc=musl -jar microctl.jar
      - name: Test Run
        shell: bash
        run: ./microctl version
      - uses: actions/upload-artifact@v2
        with:
          name: microctl-alpine
          path: microctl/microctl

  windows:
    name: "Build Windows Binary"
    needs: build
    runs-on: windows-2016
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Download Jar
        uses: actions/download-artifact@v2
        with:
          name: microctl.jar
      - name: Install GraalVM Native Image
        shell: bash
        run: .github/scripts/native/graalvm-win.sh
      - name: Build Binary
        shell: bash
        run: .github/scripts/native/native.bat
      - name: Test Run
        shell: bash
        run: ./microctl.exe version
      - uses: actions/upload-artifact@v2
        with:
          name: microctl-windows
          path: microctl.exe

  macos:
    name: "Build MacOS Binary"
    needs: build
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Download Jar
        uses: actions/download-artifact@v2
        with:
          name: microctl.jar
      - name: Install GraalVM Native Image
        shell: bash
        run: .github/scripts/native/graalvm-mac.sh
      - name: Build Binary
        shell: bash
        run: .graalvm/bin/native-image -jar microctl.jar
      - name: Test Run
        shell: bash
        run: ./microctl version
      - uses: actions/upload-artifact@v2
        with:
          name: microctl-macos
          path: ./microctl

  release:
    name: "Create release"
    needs: [linux, macos, windows, alpine]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: MicroCTL Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Download Jar
        uses: actions/download-artifact@v2
        with:
          name: microctl.jar
      - name: Upload Jar Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: microctl.jar
          asset_name: microctl.jar
          asset_content_type: application/java-archive

      - name: Download Linux Binary
        uses: actions/download-artifact@v2
        with:
          name: microctl-linux
      - name: Zip
        shell: bash
        run: zip -m microctl-linux.zip microctl
      - name: Upload Release Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: microctl-linux.zip
          asset_name: microctl-linux.zip
          asset_content_type: application/zip

      - name: Download MacOS Binary
        uses: actions/download-artifact@v2
        with:
          name: microctl-macos
      - name: Zip
        shell: bash
        run: zip -m microctl-macos.zip microctl
      - name: Upload Release Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: microctl-macos.zip
          asset_name: microctl-macos.zip
          asset_content_type: application/zip

      - name: Download Windows Binary
        uses: actions/download-artifact@v2
        with:
          name: microctl-windows
      - name: Zip
        shell: bash
        run: zip -m microctl-windows.zip microctl.exe
      - name: Upload Release Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: microctl-windows.zip
          asset_name: microctl-windows.zip
          asset_content_type: application/zip

      - name: Download Alpine Binary
        uses: actions/download-artifact@v2
        with:
          name: microctl-alpine
      - name: Zip
        shell: bash
        run: zip -m microctl-alpine.zip microctl
      - name: Upload Release Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: microctl-alpine.zip
          asset_name: microctl-alpine.zip
          asset_content_type: application/zip
